In [1]:
import cv2

In [2]:
# flag --> 0 --> gray scale and 1--> default for rgb
path = "hello.jpg"
img = cv2.imread(path, 1)

In [10]:
print(img)


[[[153 138 146]
  [154 139 147]
  [154 139 147]
  ...
  [224 206 177]
  [226 205 177]
  [224 203 175]]

 [[154 139 147]
  [153 138 146]
  [153 138 146]
  ...
  [224 206 177]
  [226 205 177]
  [224 203 175]]

 [[154 138 149]
  [152 136 147]
  [151 135 146]
  ...
  [225 205 174]
  [225 205 174]
  [224 204 173]]

 ...

 [[119 104 118]
  [118 105 119]
  [119 104 118]
  ...
  [147 138 158]
  [148 139 159]
  [150 141 161]]

 [[120 103 116]
  [116 102 114]
  [116  99 112]
  ...
  [146 137 157]
  [147 138 158]
  [148 139 159]]

 [[121 104 117]
  [119 102 115]
  [116  99 112]
  ...
  [146 137 157]
  [145 136 156]
  [145 136 156]]]


In [11]:
cv2.imshow("image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [13]:
path = "hello.jpg"
img = cv2.imread(path, 0)
cv2.imshow("image", img)
print(img.shape)
cv2.waitKey(0)
cv2.destroyAllWindows()

(480, 640)


In [15]:
path = "hello.jpg"
img = cv2.imread(path, 1)
cv2.imshow("image", img)
print(img.shape)
cv2.waitKey(0)
cv2.destroyAllWindows()

(480, 640, 3)


In [16]:
# -1 --> read image same as input
path = "hello.jpg"
img = cv2.imread(path, -1)
cv2.imshow("image", img)
print(img.shape)
cv2.waitKey(0)
cv2.destroyAllWindows()

(480, 640, 3)


In [2]:

path = r"D:\Desktop\profile.png"
img = cv2.imread(path, 1)
cv2.imshow("image", img)
print(img.shape)
cv2.waitKey(0)
cv2.destroyAllWindows()

(673, 679, 3)


# imshow function

In [18]:
# syntax: cv2.imshow(window_name, nd array)

In [3]:
import numpy as np

In [4]:
matx = np.zeros((200, 200))

In [5]:
matx

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [23]:
cv2.imshow("image", matx)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [24]:
img = cv2.imread(path)
cv2.imshow("image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
img = cv2.imread(path)
cv2.imshow("image", img)
cv2.imshow("image_matx", matx)
cv2.waitKey(0)
cv2.destroyAllWindows()